{% set name = "diffsitter" %}
{% set version = "0.8.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/afnanenayet/diffsitter/releases/download/v{{ version }}/diffsitter_src.tar.gz
  sha256: b3834648beec6f9f97e18dfe8452489a190a91c078a412c0609ecd33f43232ec

build:
  number: 0

requirements:
  build:
    - {{ compiler('rust') }}
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - git-lfs
    - cargo-bundle-licenses

test:
  commands:
    - diffsitter --help

about:
  home: https://github.com/afnanenayet/diffsitter
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: A tree-sitter based AST difftool to get meaningful semantic diffs
  home: https://github.com/afnanenayet/diffsitter

extra:
  recipe-maintainers:
    - danielnachun
