context:
  version: "0.9.0"

package:
  name: diffsitter
  version: ${{ version }}

source:
  url: https://github.com/afnanenayet/diffsitter/releases/download/v${{ version }}/diffsitter_src.tar.gz
  sha256: bcb7dc399682b5ab33826d0a993646a7405fa89290d6e768010000773b730d6e

build:
  number: 1

requirements:
  build:
    - ${{ compiler('rust') }}
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
    - git-lfs
    - cargo-bundle-licenses

tests:
  - script:
      - diffsitter --help

about:
  license: MIT
  license_file:
    - LICENSE
    - THIRDPARTY.yml
  summary: A tree-sitter based AST difftool to get meaningful semantic diffs
  homepage: https://github.com/afnanenayet/diffsitter
  repository: https://github.com/afnanenayet/diffsitter

extra:
  recipe-maintainers:
    - danielnachun
